[package]
name = "saphi_custom_tracks"
version = "1.0.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.7", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
md-5 = "0.10.6"
