"""add_video_column_to_custom_track

Revision ID: 25df28a6baf6
Revises: 7f03cccf95fb
Create Date: 2025-03-23 00:57:40.683072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df28a6baf6'
down_revision = '7f03cccf95fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_tracks', schema=None) as batch_op:
        batch_op.drop_column('video')

    # ### end Alembic commands ###
