//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::custom_tracks::Entity as CustomTracks;
pub use super::permissions::Entity as Permissions;
pub use super::resources::Entity as Resources;
pub use super::settings::Entity as Settings;
pub use super::tags::Entity as Tags;
pub use super::tags_to_custom_tracks::Entity as TagsToCustomTracks;
pub use super::users::Entity as Users;
